basePath: /v1
definitions:
  entity.Word:
    properties:
      post+id:
        type: string
      word:
        type: string
    type: object
  v1.response:
    properties:
      error:
        example: message
        type: string
    type: object
  v1.wordResponse:
    properties:
      word:
        items:
          $ref: '#/definitions/entity.Word'
        type: array
    type: object
host: 127.0.0.1:8080
info:
  contact: {}
  description: Service for find most freq words
  title: Post checker
  version: "1.0"
paths:
  /post/{post_id}/comments/statistics:
    get:
      consumes:
      - application/json
      description: Get post statistic for most frequently posts.
      operationId: post_statistic
      parameters:
      - description: Id of specific post
        in: path
        name: post_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.wordResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Get post statistic
      tags:
      - Post
swagger: "2.0"
